version: 2
updates:
  - package-ecosystem: 'gradle'
    directory: '/'
    assignees:
      - "fwilhe2"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: 'daily'
      time: "18:00"
