name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@master
    - name: Run a multi-line script
      run: |
        ./gradlew check publishMavenPublicationToGithubRepository --no-daemon --scan
      env:
        GPR_AUTH_TOKEN: ${{secrets.GPR_AUTH_TOKEN}}