name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: joschi/setup-jdk@v2
        with:
          java-version: 14
          architecture: x64
      - run: ./gradlew -v
      - uses: fwilhe2/mk@init
