name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@master
    - uses: gradle/wrapper-validation-action@v1
    - name: Test
      run: |
        ./gradlew check
