name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: joschi/setup-jdk@v2
        with:
          java-version: 15
          architecture: x64
      - name: Build
        uses: fwilhe2/setup-kotlin@main
        with:
          script: |
              #!/usr/bin/env kotlin
              @file:Repository("https://dl.bintray.com/jakubriegel/kotlin-shell")
              @file:DependsOn("eu.jrie.jetbrains:kotlin-shell-core:0.2.1")
              @file:DependsOn("org.slf4j:slf4j-simple:1.7.28")
              @file:CompilerOptions("-Xopt-in=kotlin.RequiresOptIn")
              @file:OptIn(kotlinx.coroutines.ExperimentalCoroutinesApi::class)

              import eu.jrie.jetbrains.kotlinshell.shell.*

              val timestamp = java.time.Instant.now()

              shell {
                readonly export("TIMESTAMP" to timestamp.toString())
                "./gradlew check"()
                "ls -la"()
                "echo TIMESTAMP: ${env("TIMESTAMP")}"()
                "echo GITHUB_REF: ${env("GITHUB_REF")}"()

                "mkdir -p public/testresults/${env("TIMESTAMP")}"()
                "find build/reports/tests"()
                "cp -r build/reports/tests/allTests public/testresults/${env("TIMESTAMP")}"()
                "curl https://raw.githubusercontent.com/fwilhe2/Inzell/gh-pages/index.html > public/index.html.old"()
                """cat > public/index.html.new <<EOL
                    <p>
                      <a href="testresults/${env("TIMESTAMP")}">Test results for branch ${env("GITHUB_REF")} from ${env("TIMESTAMP")}</a>
                    </p>
                EOL"""()
                "cat public/index.html* > public/index.html"()
                "rm public/index.html.*"()
              }

